# This workflow will do a clean installation of node dependencies, cache/restore them, and run hardhat tests on Arrow contracts

name: Hardhat Tests

on:
  push:
  pull_request:
  schedule:
    # run this workflow every Monday at 1PM UTC
    - cron: "* 13 * * 1"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run hardhat tests
        run: npm run test
